services:
  client:
    environment:
      - API_URL=http://api_gateway:3001
    build:
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - "3000:3000"
    env_file: 
      - .env

  api_gateway:
    environment:
      - GRPC_ENDPOINT=grpc_server:50051
    build:
      context: .
      dockerfile: ./src/api_gateway/Dockerfile
    ports:
      - "3001:3001"
    env_file: 
      - .env
    depends_on:
      - client

  grpc_server:
    build:
      context: .
      dockerfile: ./src/grpc_server/Dockerfile
    ports:
      - "50051:50051"
    env_file: 
      - .env
    depends_on:
      - api_gateway

networks:
  default:
    external:
      name: my-net
