name: Deploy to GCP

on:
  push:
    branches:
      - 39-containerize-and-deploy-app-with-all-services

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Setup Environment Variables
      run: |
        echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
        echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
        echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> .env
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env 

    - name: Build and Push Docker Compose services
      run: |
        docker-compose build
        docker-compose push
    - name: List directory contents for debugging
      run: |
        ls -al

    - name: Copy docker-compose file to GCP VM
      run: |
        cd $GITHUB_WORKSPACE
        gcloud compute scp docker-compose.yml ${{ secrets.GCP_VM_INSTANCE }}:/home/richarsamu1/ --zone=${{ secrets.GCP_VM_ZONE }}


    - name: Deploy to GCP
      run: |
        gcloud compute ssh ${{ secrets.GCP_VM_INSTANCE }} --zone=${{ secrets.GCP_VM_ZONE }} --command="sudo docker-compose pull && sudo docker-compose up -d" --quiet
